# =====================================================================================================================
# Created Syst: macOS Monterey 12.5 (21G72) Kernel: Darwin 21.6.0
# Created By  : Jeromie Kirchoff
# Created Date: Tue Aug  9 15:10:00 2022 CDT
# Last ModDate: Wed Aug 10 16:33:01 2022 CDT
# =====================================================================================================================
# Notes: city Table # city State (232 USA)
# =====================================================================================================================
DROP TABLE IF EXISTS `MyPeople`.`city`;
CREATE TABLE `MyPeople`.`city` (
    `pik`                       INT             NOT NULL AUTO_INCREMENT,
    `city_id`                   INT             DEFAULT NULL,
    `city`                      VARCHAR(256)    NOT NULL,
    `state_id`                  INT             DEFAULT NULL,
    `state`                     VARCHAR(256)    NOT NULL,
    `created_date`              DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP                             COMMENT 'Creation Date Of Record In A DateTime Format.',
    `last_modified_date`        DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Modification Date Of Record Being Changed In A DateTime Format.',
    `created_timestamp`         TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP                             COMMENT 'Creation Date Of Record In A Timestamp Format.',
    `lastmodified_timestamp`    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last Modification Date Of Record Being Changed In A Timestamp Format.',
    PRIMARY KEY (`pik`)
)   ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
    COMMENT 'List of States of city States Table.
# Note that 8 states do not have standard abbreviations: Alaska, Hawaii, Idaho, Iowa, Maine, Ohio, Texas, and Utah.
# Note that 5 states are not part of the union. (Canal Zone, District Of Columbia, Guam, Puerto Rico, Virgin Islands.'
;

# =====================================================================================================================
# city State Index
# =====================================================================================================================
ALTER TABLE `city` ADD KEY        `idx_city` (`city`);
ALTER TABLE `city` ADD UNIQUE KEY `udx_city_state` (`city`, `state`);


INSERT INTO `MyPeople`.`city` ( `city`,`state`)
VALUES
("Abbeville", "Louisiana"),
("Abbeville", "South Carolina"),
("Aberdeen", "Maryland"),
("Aberdeen", "South Dakota"),
("Aberdeen", "Washington"),
("Abilene", "Kansas"),
("Abilene", "Texas"),
("Abingdon", "Virginia"),
("Abington", "Massachusetts"),
("Abington", "Pennsylvania"),
("Acoma", "New Mexico"),
("Ada", "Oklahoma"),
("Adams", "Massachusetts"),
("Adrian", "Michigan"),
("Aiken", "South Carolina"),
("Ajo", "Arizona"),
("Akron", "Ohio"),
("Alameda", "California"),
("Alamogordo", "New Mexico"),
("Alamosa", "Colorado"),
("Albany", "Georgia"),
("Albany", "New York"),
("Albany", "Oregon"),
("Albert Lea", "Minnesota"),
("Albuquerque", "New Mexico"),
("Alcoa", "Tennessee"),
("Alexander City", "Alabama"),
("Alexandria", "Louisiana"),
("Alexandria", "Minnesota"),
("Alexandria", "Virginia"),
("Alhambra", "California"),
("Aliquippa", "Pennsylvania"),
("Allentown", "Pennsylvania"),
("Alliance", "Ohio"),
("Alma", "Michigan"),
("Alpine", "Texas"),
("Alta", "Utah"),
("Alton", "Illinois"),
("Altoona", "Pennsylvania"),
("Altus", "Oklahoma"),
("Alva", "Oklahoma"),
("Amana Colonies", "Iowa"),
("Amarillo", "Texas"),
("Ambridge", "Pennsylvania"),
("American Fork", "Utah"),
("Americus", "Georgia"),
("Ames", "Iowa"),
("Amesbury", "Massachusetts"),
("Amherst", "Massachusetts"),
("Amsterdam", "New York"),
("Anaconda", "Montana"),
("Anacortes", "Washington"),
("Anadarko", "Oklahoma"),
("Anaheim", "California"),
("Anchorage", "Alaska"),
("Andalusia", "Alabama"),
("Anderson", "Indiana"),
("Anderson", "South Carolina"),
("Andersonville", "Georgia"),
("Andover", "Massachusetts"),
("Ann Arbor", "Michigan"),
("Annapolis", "Maryland"),
("Anniston", "Alabama"),
("Ansonia", "Connecticut"),
("Antioch", "California"),
("Apalachicola", "Florida"),
("Appleton", "Wisconsin"),
("Arcadia", "California"),
("Ardmore", "Oklahoma"),
("Arkadelphia", "Arkansas"),
("Arkansas City", "Kansas"),
("Arkansas Post", "Arkansas"),
("Arlington Heights", "Illinois"),
("Arlington", "Massachusetts"),
("Arlington", "Texas"),
("Artesia", "New Mexico"),
("Arthur", "Illinois"),
("Asbury Park", "New Jersey"),
("Asheboro", "North Carolina"),
("Asheville", "North Carolina"),
("Ashland", "Kentucky"),
("Ashland", "Oregon"),
("Ashland", "Wisconsin"),
("Ashtabula", "Ohio"),
("Aspen", "Colorado"),
("Astoria", "Oregon"),
("Atchison", "Kansas"),
("Athens", "Alabama"),
("Athens", "Georgia"),
("Athens", "Ohio"),
("Athens", "Tennessee"),
("Athol", "Massachusetts"),
("Atlanta", "Georgia"),
("Atlantic City", "New Jersey"),
("Atmore", "Alabama"),
("Attleboro", "Massachusetts"),
("Auburn", "Alabama"),
("Auburn", "Maine"),
("Auburn", "New York"),
("Auburn", "Washington"),
("Augusta", "Georgia"),
("Augusta", "Maine"),
("Aurora", "Colorado"),
("Aurora", "Illinois"),
("Austin", "Minnesota"),
("Austin", "Texas"),
("Avondale", "Arizona"),
("Babylon", "New York"),
("Bainbridge", "Georgia"),
("Baker City", "Oregon"),
("Bakersfield", "California"),
("Baltimore", "Maryland"),
("Bangor", "Maine"),
("Bar Harbor", "Maine"),
("Baraboo", "Wisconsin"),
("Barberton", "Ohio"),
("Barbourville", "Kentucky"),
("Bardstown", "Kentucky"),
("Barnstable", "Massachusetts"),
("Barre", "Vermont"),
("Barrington", "Rhode Island"),
("Barstow", "California"),
("Bartlesville", "Oklahoma"),
("Bartow", "Florida"),
("Bastrop", "Louisiana"),
("Batavia", "New York"),
("Batesville", "Arkansas"),
("Bath", "Maine"),
("Bath", "North Carolina"),
("Bath", "West Virginia"),
("Baton Rouge", "Louisiana"),
("Battle Creek", "Michigan"),
("Bay City", "Michigan"),
("Bay Saint Louis", "Mississippi"),
("Bayonne", "New Jersey"),
("Baytown", "Texas"),
("Beacon", "New York"),
("Beatrice", "Nebraska"),
("Beaufort", "North Carolina"),
("Beaufort", "South Carolina"),
("Beaumont", "Texas"),
("Beaverton", "Oregon"),
("Beckley", "West Virginia"),
("Bedford", "Indiana"),
("Bedford", "Massachusetts"),
("Bedford", "New York"),
("Bedford", "Ohio"),
("Bedford", "Pennsylvania"),
("Belen", "New Mexico"),
("Belfast", "Maine"),
("Belle Fourche", "South Dakota"),
("Belle Glade", "Florida"),
("Bellefontaine", "Ohio"),
("Belleville", "Illinois"),
("Bellevue", "Nebraska"),
("Bellevue", "Washington"),
("Bellingham", "Washington"),
("Bellows Falls", "Vermont"),
("Belmont", "California"),
("Belmont", "Wisconsin"),
("Beloit", "Wisconsin"),
("Belvidere", "Illinois"),
("Bemidji", "Minnesota"),
("Bend", "Oregon"),
("Bennington", "Vermont"),
("Benton Harbor", "Michigan"),
("Benton", "Arkansas"),
("Berea", "Kentucky"),
("Berkeley", "California"),
("Berlin", "Connecticut"),
("Berlin", "New Hampshire"),
("Bessemer", "Alabama"),
("Bethany", "Oklahoma"),
("Bethesda-Chevy Chase", "Maryland"),
("Bethlehem", "Pennsylvania"),
("Beverly Hills", "California"),
("Beverly", "Massachusetts"),
("Biddeford", "Maine"),
("Big Spring", "Texas"),
("Billings", "Montana"),
("Biloxi", "Mississippi"),
("Binghamton", "New York"),
("Birmingham", "Alabama"),
("Bisbee", "Arizona"),
("Bismarck", "North Dakota"),
("Blackfoot", "Idaho"),
("Blairsville", "Georgia"),
("Bloomfield Hills", "Michigan"),
("Bloomfield", "Connecticut"),
("Bloomfield", "New Jersey"),
("Bloomington", "Illinois"),
("Bloomington", "Indiana"),
("Bloomington", "Minnesota"),
("Bloomsburg", "Pennsylvania"),
("Bluefield", "West Virginia"),
("Blytheville", "Arkansas"),
("Boca Raton", "Florida"),
("Bogalusa", "Louisiana"),
("Boise", "Idaho"),
("Bonners Ferry", "Idaho"),
("Boone", "Iowa"),
("Boone", "North Carolina"),
("Boonesborough", "Kentucky"),
("Boonville", "Missouri"),
("Boothbay Harbor", "Maine"),
("Bordentown", "New Jersey"),
("Borger", "Texas"),
("Bossier City", "Louisiana"),
("Boston", "Massachusetts"),
("Boulder City", "Nevada"),
("Boulder", "Colorado"),
("Bound Brook", "New Jersey"),
("Bountiful", "Utah"),
("Bourne", "Massachusetts"),
("Bowie", "Maryland"),
("Bowling Green", "Kentucky"),
("Bowling Green", "Ohio"),
("Boys Town", "Nebraska"),
("Bozeman", "Montana"),
("Bradenton", "Florida"),
("Bradford", "Pennsylvania"),
("Brainerd", "Minnesota"),
("Braintree", "Massachusetts"),
("Branford", "Connecticut"),
("Branson", "Missouri"),
("Brattleboro", "Vermont"),
("Brea", "California"),
("Breckenridge", "Colorado"),
("Bremerton", "Washington"),
("Bridgeport", "Connecticut"),
("Bridgeton", "New Jersey"),
("Brigham City", "Utah"),
("Brighton", "Colorado"),
("Bristol", "Connecticut"),
("Bristol", "Pennsylvania"),
("Bristol", "Rhode Island"),
("Bristol", "Virginia"),
("Brockton", "Massachusetts"),
("Bronx", "New York"),
("Brookfield", "Illinois"),
("Brookings", "Oregon"),
("Brookings", "South Dakota"),
("Brookline", "Massachusetts"),
("Brooklyn", "New York"),
("Brownsville", "Texas"),
("Brunswick", "Georgia"),
("Brunswick", "Maine"),
("Bryan", "Texas"),
("Buckhannon", "West Virginia"),
("Buena Park", "California"),
("Buffalo", "New York"),
("Buffalo", "Wyoming"),
("Burbank", "California"),
("Burlington", "Iowa"),
("Burlington", "New Jersey"),
("Burlington", "North Carolina"),
("Burlington", "Vermont"),
("Burns", "Oregon"),
("Butte", "Montana"),
("Cadillac", "Michigan"),
("Cahokia", "Illinois"),
("Cairo", "Illinois"),
("Calais", "Maine"),
("Caldwell", "Idaho"),
("Caldwell", "New Jersey"),
("Calexico", "California"),
("Calhoun", "Georgia"),
("Calistoga", "California"),
("Calumet City", "Illinois"),
("Cambridge", "Maryland"),
("Cambridge", "Massachusetts"),
("Camden", "Arkansas"),
("Camden", "New Jersey"),
("Camden", "South Carolina"),
("Campbellsville", "Kentucky"),
("Canon City", "Colorado"),
("Canton", "Illinois"),
("Canton", "Massachusetts"),
("Canton", "Mississippi"),
("Canton", "Ohio"),
("Canton", "South Dakota"),
("Canyon", "Texas"),
("Cape Coral", "Florida"),
("Cape Girardeau", "Missouri"),
("Cape May", "New Jersey"),
("Carbondale", "Illinois"),
("Carbondale", "Pennsylvania"),
("Caribou", "Maine"),
("Carlinville", "Illinois"),
("Carlisle", "Pennsylvania"),
("Carlsbad", "California"),
("Carlsbad", "New Mexico"),
("Carmel", "California"),
("Carrollton", "Georgia"),
("Carson City", "Nevada"),
("Carthage", "Illinois"),
("Carthage", "Missouri"),
("Casa Grande", "Arizona"),
("Casper", "Wyoming"),
("Castine", "Maine"),
("Catonsville", "Maryland"),
("Cedar City", "Utah"),
("Cedar Falls", "Iowa"),
("Cedar Rapids", "Iowa"),
("Central City", "Colorado"),
("Central Falls", "Rhode Island"),
("Centralia", "Illinois"),
("Centralia", "Washington"),
("Chadron", "Nebraska"),
("Chambersburg", "Pennsylvania"),
("Champaign", "Illinois"),
("Chandler", "Arizona"),
("Chanute", "Kansas"),
("Chapel Hill", "North Carolina"),
("Charles City", "Iowa"),
("Charles Town", "West Virginia"),
("Charleston", "Illinois"),
("Charleston", "South Carolina"),
("Charleston", "West Virginia"),
("Charlestown", "Massachusetts"),
("Charlevoix", "Michigan"),
("Charlotte", "North Carolina"),
("Charlottesville", "Virginia"),
("Chattanooga", "Tennessee"),
("Chautauqua", "New York"),
("Cheboygan", "Michigan"),
("Cheektowaga", "New York"),
("Chelmsford", "Massachusetts"),
("Chelsea", "Massachusetts"),
("Cherokee", "Iowa"),
("Chesapeake", "Virginia"),
("Chester", "Illinois"),
("Chester", "Pennsylvania"),
("Cheyenne", "Wyoming"),
("Chicago Heights", "Illinois"),
("Chicago", "Illinois"),
("Chickasaw", "Alabama"),
("Chickasha", "Oklahoma"),
("Chico", "California"),
("Chicopee", "Massachusetts"),
("Chillicothe", "Missouri"),
("Chillicothe", "Ohio"),
("Chula Vista", "California"),
("Cicero", "Illinois"),
("Cincinnati", "Ohio"),
("Clanton", "Alabama"),
("Claremont", "California"),
("Claremont", "New Hampshire"),
("Claremore", "Oklahoma"),
("Clarksburg", "West Virginia"),
("Clarksdale", "Mississippi"),
("Clarksville", "Tennessee"),
("Clayton", "Missouri"),
("Clearfield", "Utah"),
("Clearwater", "Florida"),
("Cleburne", "Texas"),
("Cleveland Heights", "Ohio"),
("Cleveland", "Ohio"),
("Cleveland", "Tennessee"),
("Clifton", "Arizona"),
("Clifton", "New Jersey"),
("Climax", "Colorado"),
("Clinton", "Iowa"),
("Clinton", "Massachusetts"),
("Clinton", "New York"),
("Clinton", "Oklahoma"),
("Clovis", "New Mexico"),
("Cocoa Beach", "Florida"),
("Cocoa-Rockledge", "Florida"),
("Cody", "Wyoming"),
("Coeur d’Alene", "Idaho"),
("Coffeyville", "Kansas"),
("Cohasset", "Massachusetts"),
("Cohoes", "New York"),
("College Park", "Maryland"),
("College Station", "Texas"),
("Collinsville", "Illinois"),
("Colorado Springs", "Colorado"),
("Columbia", "Maryland"),
("Columbia", "Mississippi"),
("Columbia", "Missouri"),
("Columbia", "Pennsylvania"),
("Columbia", "South Carolina"),
("Columbia", "Tennessee"),
("Columbus", "Georgia"),
("Columbus", "Indiana"),
("Columbus", "Mississippi"),
("Columbus", "Nebraska"),
("Columbus", "Ohio"),
("Compton", "California"),
("Concord", "California"),
("Concord", "Massachusetts"),
("Concord", "New Hampshire"),
("Concord", "North Carolina"),
("Coney Island", "New York"),
("Conneaut", "Ohio"),
("Connersville", "Indiana"),
("Conway", "Arkansas"),
("Cookeville", "Tennessee"),
("Cooperstown", "New York"),
("Coos Bay", "Oregon"),
("Coral Gables", "Florida"),
("Cordova", "Alaska"),
("Corinth", "Mississippi"),
("Corning", "New York"),
("Corona", "California"),
("Coronado", "California"),
("Corpus Christi", "Texas"),
("Cortez", "Colorado"),
("Cortland", "New York"),
("Corvallis", "Oregon"),
("Corydon", "Indiana"),
("Costa Mesa", "California"),
("Coulee Dam", "Washington"),
("Council Bluffs", "Iowa"),
("Council Grove", "Kansas"),
("Coupeville", "Washington"),
("Coventry", "Connecticut"),
("Covington", "Kentucky"),
("Cranford", "New Jersey"),
("Cranston", "Rhode Island"),
("Crawfordsville", "Indiana"),
("Cripple Creek", "Colorado"),
("Crookston", "Minnesota"),
("Crossett", "Arkansas"),
("Crown Point", "New York"),
("Crystal City", "Texas"),
("Cullman", "Alabama"),
("Culver City", "California"),
("Cumberland", "Maryland"),
("Cushing", "Oklahoma"),
("Custer", "South Dakota"),
("Cuyahoga Falls", "Ohio"),
("Dahlonega", "Georgia"),
("Dallas", "Texas"),
("Dalton", "Georgia"),
("Daly City", "California"),
("Danbury", "Connecticut"),
("Danvers", "Massachusetts"),
("Danville", "Illinois"),
("Danville", "Kentucky"),
("Danville", "Virginia"),
("Darien", "Connecticut"),
("Darien", "Georgia"),
("Darlington", "South Carolina"),
("Dartmouth", "Massachusetts"),
("Davenport", "Iowa"),
("Davis", "California"),
("Dayton", "Ohio"),
("Dayton", "Tennessee"),
("Daytona Beach", "Florida"),
("De Land", "Florida"),
("De Smet", "South Dakota"),
("Deadwood", "South Dakota"),
("Dearborn", "Michigan"),
("Decatur", "Alabama"),
("Decatur", "Georgia"),
("Decatur", "Illinois"),
("Dedham", "Massachusetts"),
("Deerfield Beach", "Florida"),
("Defiance", "Ohio"),
("DeKalb", "Illinois"),
("Del Rio", "Texas"),
("Delaware", "Ohio"),
("Delray Beach", "Florida"),
("Delta", "Utah"),
("Deming", "New Mexico"),
("Demopolis", "Alabama"),
("Denison", "Texas"),
("Dennis", "Massachusetts"),
("Denton", "Texas"),
("Denver", "Colorado"),
("Derby", "Connecticut"),
("Derry", "New Hampshire"),
("Des Moines", "Iowa"),
("Des Plaines", "Illinois"),
("Detroit", "Michigan"),
("Devils Lake", "North Dakota"),
("Dickinson", "North Dakota"),
("Dillon", "Montana"),
("Dixon", "Illinois"),
("Dodge City", "Kansas"),
("Dothan", "Alabama"),
("Douglas", "Arizona"),
("Douglas", "Georgia"),
("Douglas", "Wyoming"),
("Dover", "Delaware"),
("Dover", "New Hampshire"),
("Downey", "California"),
("Dubuque", "Iowa"),
("Duluth", "Minnesota"),
("Duncan", "Oklahoma"),
("Dunkirk", "New York"),
("Durango", "Colorado"),
("Durant", "Oklahoma"),
("Durham", "New Hampshire"),
("Durham", "North Carolina"),
("Duxbury", "Massachusetts"),
("Eagle Pass", "Texas"),
("East Aurora", "New York"),
("East Chicago", "Indiana"),
("East Cleveland", "Ohio"),
("East Greenwich", "Rhode Island"),
("East Hampton", "New York"),
("East Hartford", "Connecticut"),
("East Haven", "Connecticut"),
("East Lansing", "Michigan"),
("East Liverpool", "Ohio"),
("East Moline", "Illinois"),
("East Orange", "New Jersey"),
("East Point", "Georgia"),
("East Providence", "Rhode Island"),
("East Saint Louis", "Illinois"),
("Eastchester", "New York"),
("Eastham", "Massachusetts"),
("Easton", "Maryland"),
("Easton", "Pennsylvania"),
("Eastpointe", "Michigan"),
("Eastport", "Maine"),
("Eau Claire", "Wisconsin"),
("Ecorse", "Michigan"),
("Edenton", "North Carolina"),
("Edgartown", "Massachusetts"),
("Edinburg", "Texas"),
("Edison", "New Jersey"),
("Edmond", "Oklahoma"),
("Effingham", "Illinois"),
("El Centro", "California"),
("El Cerrito", "California"),
("El Dorado", "Arkansas"),
("El Monte", "California"),
("El Paso", "Texas"),
("El Reno", "Oklahoma"),
("Elgin", "Illinois"),
("Elizabeth City", "North Carolina"),
("Elizabeth", "New Jersey"),
("Elizabethton", "Tennessee"),
("Elizabethtown", "Kentucky"),
("Elk City", "Oklahoma"),
("Elkhart", "Indiana"),
("Elkins", "West Virginia"),
("Elko", "Nevada"),
("Elkton", "Maryland"),
("Ellensburg", "Washington"),
("Ellsworth", "Maine"),
("Elmhurst", "Illinois"),
("Elmira", "New York"),
("Elwood", "Indiana"),
("Ely", "Minnesota"),
("Ely", "Nevada"),
("Elyria", "Ohio"),
("Emmitsburg", "Maryland"),
("Emporia", "Kansas"),
("Enfield", "Connecticut"),
("Englewood", "Colorado"),
("Englewood", "New Jersey"),
("Enid", "Oklahoma"),
("Enterprise", "Alabama"),
("Ephrata", "Washington"),
("Erie", "Pennsylvania"),
("Escanaba", "Michigan"),
("Escondido", "California"),
("Essex", "Vermont"),
("Estes Park", "Colorado"),
("Estherville", "Iowa"),
("Euclid", "Ohio"),
("Eufaula", "Alabama"),
("Eufaula", "Oklahoma"),
("Eugene", "Oregon"),
("Eureka", "California"),
("Evanston", "Illinois"),
("Evanston", "Wyoming"),
("Evansville", "Indiana"),
("Eveleth", "Minnesota"),
("Everett", "Massachusetts"),
("Everett", "Washington"),
("Excelsior Springs", "Missouri"),
("Exeter", "New Hampshire"),
("Fairbanks", "Alaska"),
("Fairfax", "Virginia"),
("Fairfield", "California"),
("Fairfield", "Connecticut"),
("Fairfield", "Iowa"),
("Fairhaven", "Massachusetts"),
("Fairmont", "West Virginia"),
("Fall River", "Massachusetts"),
("Fallon", "Nevada"),
("Falls Church", "Virginia"),
("Falmouth", "Massachusetts"),
("Fargo", "North Dakota"),
("Faribault", "Minnesota"),
("Farmington", "Connecticut"),
("Farmington", "Maine"),
("Farmington", "New Mexico"),
("Fayetteville", "Arkansas"),
("Fayetteville", "North Carolina"),
("Fergus Falls", "Minnesota"),
("Ferguson", "Missouri"),
("Fernandina Beach", "Florida"),
("Fillmore", "Utah"),
("Findlay", "Ohio"),
("Fitchburg", "Massachusetts"),
("Fitzgerald", "Georgia"),
("Flagstaff", "Arizona"),
("Flint", "Michigan"),
("Florence", "Alabama"),
("Florence", "Arizona"),
("Florence", "South Carolina"),
("Florissant", "Missouri"),
("Flushing", "New York"),
("Fond du Lac", "Wisconsin"),
("Fontana", "California"),
("Forest Hills", "New York"),
("Forrest City", "Arkansas"),
("Fort Benton", "Montana"),
("Fort Collins", "Colorado"),
("Fort Dodge", "Iowa"),
("Fort Kent", "Maine"),
("Fort Lauderdale", "Florida"),
("Fort Lee", "New Jersey"),
("Fort Morgan", "Colorado"),
("Fort Myers", "Florida"),
("Fort Payne", "Alabama"),
("Fort Pierce", "Florida"),
("Fort Scott", "Kansas"),
("Fort Smith", "Arkansas"),
("Fort Valley", "Georgia"),
("Fort Walton Beach", "Florida"),
("Fort Wayne", "Indiana"),
("Fort Worth", "Texas"),
("Framingham", "Massachusetts"),
("Frankfort", "Kentucky"),
("Franklin", "New Hampshire"),
("Franklin", "Pennsylvania"),
("Franklin", "Tennessee"),
("Frederick", "Maryland"),
("Frederick", "Oklahoma"),
("Fredericksburg", "Virginia"),
("Fredonia", "New York"),
("Freeport", "Illinois"),
("Freeport", "Texas"),
("Fremont", "California"),
("Fremont", "Nebraska"),
("French Lick", "Indiana"),
("Fresno", "California"),
("Fullerton", "California"),
("Fulton", "Missouri"),
("Gadsden", "Alabama"),
("Gaffney", "South Carolina"),
("Gainesville", "Florida"),
("Gainesville", "Georgia"),
("Galena", "Illinois"),
("Galesburg", "Illinois"),
("Gallatin", "Tennessee"),
("Gallipolis", "Ohio"),
("Gallup", "New Mexico"),
("Galveston", "Texas"),
("Garden City", "Kansas"),
("Garden City", "New York"),
("Garden Grove", "California"),
("Gardiner", "Maine"),
("Garland", "Texas"),
("Gary", "Indiana"),
("Gastonia", "North Carolina"),
("Gatlinburg", "Tennessee"),
("Geneva", "Indiana"),
("Geneva", "New York"),
("Genoa", "Nevada"),
("Georgetown", "Colorado"),
("Georgetown", "South Carolina"),
("Germantown", "Pennsylvania"),
("Gettysburg", "Pennsylvania"),
("Gila Bend", "Arizona"),
("Gillette", "Wyoming"),
("Glassboro", "New Jersey"),
("Glen Ellyn", "Illinois"),
("Glendale", "Arizona"),
("Glendale", "California"),
("Glendive", "Montana"),
("Glens Falls", "New York"),
("Glenview", "Illinois"),
("Glenwood Springs", "Colorado"),
("Globe", "Arizona"),
("Gloucester", "Massachusetts"),
("Gloversville", "New York"),
("Golden", "Colorado"),
("Goldfield", "Nevada"),
("Goldsboro", "North Carolina"),
("Goliad", "Texas"),
("Goshen", "Indiana"),
("Grafton", "West Virginia"),
("Grand Forks", "North Dakota"),
("Grand Haven", "Michigan"),
("Grand Island", "Nebraska"),
("Grand Junction", "Colorado"),
("Grand Rapids", "Michigan"),
("Granite City", "Illinois"),
("Grants Pass", "Oregon"),
("Grants", "New Mexico"),
("Grayling", "Michigan"),
("Great Barrington", "Massachusetts"),
("Great Bend", "Kansas"),
("Great Falls", "Montana"),
("Great Neck", "New York"),
("Greeley", "Colorado"),
("Green Bay", "Wisconsin"),
("Green River", "Utah"),
("Green River", "Wyoming"),
("Greenbelt", "Maryland"),
("Greeneville", "Tennessee"),
("Greenfield", "Indiana"),
("Greenfield", "Massachusetts"),
("Greensboro", "North Carolina"),
("Greensburg", "Pennsylvania"),
("Greenville", "Alabama"),
("Greenville", "Mississippi"),
("Greenville", "North Carolina"),
("Greenville", "Ohio"),
("Greenville", "South Carolina"),
("Greenville", "Texas"),
("Greenwich", "Connecticut"),
("Greenwood", "Mississippi"),
("Greenwood", "South Carolina"),
("Grenada", "Mississippi"),
("Gretna", "Louisiana"),
("Grinnell", "Iowa"),
("Grosse Pointe", "Michigan"),
("Groton", "Connecticut"),
("Groton", "Massachusetts"),
("Guilford", "Connecticut"),
("Gulfport", "Mississippi"),
("Gunnison", "Colorado"),
("Guntersville", "Alabama"),
("Guthrie", "Oklahoma"),
("Guymon", "Oklahoma"),
("Hackensack", "New Jersey"),
("Haddonfield", "New Jersey"),
("Hagerstown", "Maryland"),
("Haines", "Alaska"),
("Halifax", "North Carolina"),
("Hallandale Beach", "Florida"),
("Hamden", "Connecticut"),
("Hamilton", "Ohio"),
("Hammond", "Indiana"),
("Hammondsport", "New York"),
("Hampton", "Virginia"),
("Hanalei", "Hawaii"),
("Hancock", "Michigan"),
("Hannibal", "Missouri"),
("Hanover", "New Hampshire"),
("Hanover", "Pennsylvania"),
("Hanover", "Virginia"),
("Harlan", "Kentucky"),
("Harlem", "New York"),
("Harlingen", "Texas"),
("Harmony", "Pennsylvania"),
("Harpers Ferry", "West Virginia"),
("Harrisburg", "Illinois"),
("Harrisburg", "Pennsylvania"),
("Harrison", "Arkansas"),
("Harrodsburg", "Kentucky"),
("Hartford", "Connecticut"),
("Hartsville", "South Carolina"),
("Harwich", "Massachusetts"),
("Hastings", "Minnesota"),
("Hastings", "Nebraska"),
("Hattiesburg", "Mississippi"),
("Haverhill", "Massachusetts"),
("Havre", "Montana"),
("Hays", "Kansas"),
("Hayward", "California"),
("Hayward", "Wisconsin"),
("Hazard", "Kentucky"),
("Hazleton", "Pennsylvania"),
("Heber City", "Utah"),
("Helena", "Arkansas"),
("Helena", "Montana"),
("Hempstead", "New York"),
("Henderson", "Kentucky"),
("Henderson", "Nevada"),
("Henderson", "North Carolina"),
("Herkimer", "New York"),
("Herrin", "Illinois"),
("Hershey", "Pennsylvania"),
("Hialeah", "Florida"),
("Hibbing", "Minnesota"),
("Hickory", "North Carolina"),
("High Point", "North Carolina"),
("Highland Park", "Illinois"),
("Highland Park", "Michigan"),
("Hillsboro", "Oregon"),
("Hillsboro", "West Virginia"),
("Hillsborough", "New Hampshire"),
("Hillsborough", "North Carolina"),
("Hilo", "Hawaii"),
("Hingham", "Massachusetts"),
("Hinton", "West Virginia"),
("Hobart", "Indiana"),
("Hobart", "Oklahoma"),
("Hobbs", "New Mexico"),
("Hoboken", "New Jersey"),
("Hodgenville", "Kentucky"),
("Holdenville", "Oklahoma"),
("Holland", "Michigan"),
("Holly Springs", "Mississippi"),
("Hollywood", "California"),
("Hollywood", "Florida"),
("Holyoke", "Massachusetts"),
("Homer", "Alaska"),
("Homestead", "Florida"),
("Homestead", "Pennsylvania"),
("Honaunau", "Hawaii"),
("Honesdale", "Pennsylvania"),
("Honolulu", "Hawaii"),
("Hood River", "Oregon"),
("Hope", "Arkansas"),
("Hopewell", "Virginia"),
("Hopkinsville", "Kentucky"),
("Hoquiam", "Washington"),
("Hot Springs", "Arkansas"),
("Hot Springs", "South Dakota"),
("Houghton", "Michigan"),
("Houlton", "Maine"),
("Houma", "Louisiana"),
("Houston", "Texas"),
("Hudson", "New York"),
("Hugo", "Oklahoma"),
("Huntington Beach", "California"),
("Huntington", "Indiana"),
("Huntington", "New York"),
("Huntington", "West Virginia"),
("Huntsville", "Alabama"),
("Huntsville", "Texas"),
("Huron", "South Dakota"),
("Hutchinson", "Kansas"),
("Hyannis", "Massachusetts"),
("Hyattsville", "Maryland"),
("Hyde Park", "New York"),
("Idaho City", "Idaho"),
("Idaho Falls", "Idaho"),
("Ilion", "New York"),
("Independence", "Kansas"),
("Independence", "Missouri"),
("Indiana", "Pennsylvania"),
("Indianapolis", "Indiana"),
("Indianola", "Iowa"),
("Indio", "California"),
("Inglewood", "California"),
("Interlochen", "Michigan"),
("International Falls", "Minnesota"),
("Iowa City", "Iowa"),
("Ipswich", "Massachusetts"),
("Iron Mountain", "Michigan"),
("Ironwood", "Michigan"),
("Irvine", "California"),
("Irving", "Texas"),
("Irvington", "New Jersey"),
("Ishpeming", "Michigan"),
("Ithaca", "New York"),
("Jackson", "Michigan"),
("Jackson", "Mississippi"),
("Jackson", "Tennessee"),
("Jackson", "Wyoming"),
("Jacksonville", "Arkansas"),
("Jacksonville", "Florida"),
("Jacksonville", "Illinois"),
("Jacksonville", "North Carolina"),
("Jacksonville", "Oregon"),
("Jamestown", "New York"),
("Jamestown", "North Dakota"),
("Janesville", "Wisconsin"),
("Jasper", "Alabama"),
("Jeannette", "Pennsylvania"),
("Jefferson City", "Missouri"),
("Jeffersonville", "Indiana"),
("Jersey City", "New Jersey"),
("Jim Thorpe", "Pennsylvania"),
("John Day", "Oregon"),
("Johnson City", "Tennessee"),
("Johnson City", "Texas"),
("Johnstown", "New York"),
("Johnstown", "Pennsylvania"),
("Joliet", "Illinois"),
("Jonesboro", "Arkansas"),
("Jonesborough", "Tennessee"),
("Joplin", "Missouri"),
("Junction City", "Kansas"),
("Juneau", "Alaska"),
("Kahului", "Hawaii"),
("Kalamazoo", "Michigan"),
("Kalispell", "Montana"),
("Kanab", "Utah"),
("Kaneohe", "Hawaii"),
("Kankakee", "Illinois"),
("Kansas City", "Kansas"),
("Kansas City", "Missouri"),
("Kapaa", "Hawaii"),
("Kaskaskia", "Illinois"),
("Kawaihae", "Hawaii"),
("Kearney", "Nebraska"),
("Keene", "New Hampshire"),
("Kellogg", "Idaho"),
("Kelso", "Washington"),
("Kennebunkport", "Maine"),
("Kennewick", "Washington"),
("Kenosha", "Wisconsin"),
("Kent", "Ohio"),
("Keokuk", "Iowa"),
("Ketchikan", "Alaska"),
("Kettering", "Ohio"),
("Kewanee", "Illinois"),
("Key West", "Florida"),
("Keyser", "West Virginia"),
("Kilgore", "Texas"),
("Killeen", "Texas"),
("Kingman", "Arizona"),
("Kingsport", "Tennessee"),
("Kingston", "New York"),
("Kingston", "Rhode Island"),
("Kingsville", "Texas"),
("Kinston", "North Carolina"),
("Kirksville", "Missouri"),
("Kittery", "Maine"),
("Kitty Hawk", "North Carolina"),
("Klamath Falls", "Oregon"),
("Knoxville", "Tennessee"),
("Kodiak", "Alaska"),
("Kokomo", "Indiana"),
("Kotzebue", "Alaska"),
("La Crosse", "Wisconsin"),
("La Grande", "Oregon"),
("La Grange", "Georgia"),
("La Habra", "California"),
("La Junta", "Colorado"),
("La Salle", "Illinois"),
("Lackawanna", "New York"),
("Laconia", "New Hampshire"),
("Lafayette", "Indiana"),
("Lafayette", "Louisiana"),
("Laguna Beach", "California"),
("Lahaina", "Hawaii"),
("Laie", "Hawaii"),
("Lake Charles", "Louisiana"),
("Lake City", "Florida"),
("Lake Forest", "Illinois"),
("Lake Geneva", "Wisconsin"),
("Lake Havasu City", "Arizona"),
("Lake Oswego", "Oregon"),
("Lake Placid", "New York"),
("Lake Wales", "Florida"),
("Lakehurst", "New Jersey"),
("Lakeland", "Florida"),
("Lakeview", "Oregon"),
("Lakewood", "New Jersey"),
("Lakewood", "Ohio"),
("Lamar", "Missouri"),
("Lancaster", "California"),
("Lancaster", "Ohio"),
("Lancaster", "Pennsylvania"),
("Lancaster", "South Carolina"),
("Lander", "Wyoming"),
("Lansing", "Michigan"),
("Laramie", "Wyoming"),
("Laredo", "Texas"),
("Largo", "Florida"),
("Las Cruces", "New Mexico"),
("Las Vegas", "Nevada"),
("Las Vegas", "New Mexico"),
("Laurel", "Maryland"),
("Laurel", "Mississippi"),
("Lawrence", "Kansas"),
("Lawrence", "Massachusetts"),
("Lawton", "Oklahoma"),
("Layton", "Utah"),
("Lead", "South Dakota"),
("Leadville", "Colorado"),
("Leavenworth", "Kansas"),
("Lebanon", "Connecticut"),
("Lebanon", "Missouri"),
("Lebanon", "New Hampshire"),
("Lebanon", "Pennsylvania"),
("Lebanon", "Tennessee"),
("Lehi", "Utah"),
("Lenox", "Massachusetts"),
("Leominster", "Massachusetts"),
("Levittown", "New York"),
("Levittown", "Pennsylvania"),
("Lewes", "Delaware"),
("Lewisburg", "West Virginia"),
("Lewiston", "Idaho"),
("Lewiston", "Maine"),
("Lewistown", "Montana"),
("Lewistown", "Pennsylvania"),
("Lexington", "Kentucky"),
("Lexington", "Massachusetts"),
("Lexington", "Missouri"),
("Lexington", "Virginia"),
("Liberal", "Kansas"),
("Libertyville", "Illinois"),
("Lima", "Ohio"),
("Lincoln", "Illinois"),
("Lincoln", "Nebraska"),
("Lisle", "Illinois"),
("Litchfield", "Connecticut"),
("Little Falls", "Minnesota"),
("Little Rock", "Arkansas"),
("Littleton", "Colorado"),
("Livermore", "California"),
("Livingston", "Montana"),
("Livonia", "Michigan"),
("Lock Haven", "Pennsylvania"),
("Lockport", "New York"),
("Lodi", "California"),
("Logan", "Utah"),
("Logan", "West Virginia"),
("Lombard", "Illinois"),
("Lompoc", "California"),
("Long Beach", "California"),
("Long Beach", "New Jersey"),
("Long Branch", "New Jersey"),
("Longmont", "Colorado"),
("Longview", "Texas"),
("Longview", "Washington"),
("Lorain", "Ohio"),
("Los Alamos", "New Mexico"),
("Los Angeles", "California"),
("Louisville", "Kentucky"),
("Loveland", "Colorado"),
("Lovington", "New Mexico"),
("Lowell", "Massachusetts"),
("Lower Southampton", "Pennsylvania"),
("Lubbock", "Texas"),
("Lubec", "Maine"),
("Ludington", "Michigan"),
("Ludlow", "Massachusetts"),
("Lufkin", "Texas"),
("Lumberton", "North Carolina"),
("Lynchburg", "Virginia"),
("Lynn", "Massachusetts"),
("Machias", "Maine"),
("Mackinaw City", "Michigan"),
("Macomb", "Illinois"),
("Macon", "Georgia"),
("Madison", "Indiana"),
("Madison", "New Jersey"),
("Madison", "South Dakota"),
("Madison", "Wisconsin"),
("Magnolia", "Arkansas"),
("Malden", "Massachusetts"),
("Malibu", "California"),
("Mamaroneck", "New York"),
("Manassas", "Virginia"),
("Manchester", "Connecticut"),
("Manchester", "New Hampshire"),
("Manchester", "Vermont"),
("Mandan", "North Dakota"),
("Manhattan", "Kansas"),
("Manhattan", "New York"),
("Manistee", "Michigan"),
("Manitowoc", "Wisconsin"),
("Mankato", "Minnesota"),
("Mansfield", "Connecticut"),
("Mansfield", "Ohio"),
("Manti", "Utah"),
("Marblehead", "Massachusetts"),
("Marietta", "Georgia"),
("Marietta", "Ohio"),
("Marinette", "Wisconsin"),
("Marion", "Alabama"),
("Marion", "Indiana"),
("Marion", "Ohio"),
("Marlborough", "Massachusetts"),
("Marquette", "Michigan"),
("Marshall", "Texas"),
("Martinez", "California"),
("Martins Ferry", "Ohio"),
("Martinsburg", "West Virginia"),
("Martinsville", "Virginia"),
("Marysville", "California"),
("Maryville", "Missouri"),
("Maryville", "Tennessee"),
("Mason City", "Iowa"),
("Massena", "New York"),
("Massillon", "Ohio"),
("Mattoon", "Illinois"),
("Mayfield", "Kentucky"),
("Maysville", "Kentucky"),
("McAlester", "Oklahoma"),
("McAllen", "Texas"),
("McCook", "Nebraska"),
("McKeesport", "Pennsylvania"),
("McKinney", "Texas"),
("McMinnville", "Oregon"),
("McPherson", "Kansas"),
("Meadville", "Pennsylvania"),
("Medford", "Massachusetts"),
("Medford", "Oregon"),
("Medicine Lodge", "Kansas"),
("Melbourne", "Florida"),
("Memphis", "Tennessee"),
("Menasha", "Wisconsin"),
("Menlo Park", "California"),
("Menlo Park", "New Jersey"),
("Menominee", "Michigan"),
("Mentor", "Ohio"),
("Merced", "California"),
("Meriden", "Connecticut"),
("Meridian", "Mississippi"),
("Mesa", "Arizona"),
("Mesquite", "Texas"),
("Mexico", "Missouri"),
("Miami Beach", "Florida"),
("Miami", "Florida"),
("Miami", "Oklahoma"),
("Michigan City", "Indiana"),
("Middlebury", "Vermont"),
("Middlesboro", "Kentucky"),
("Middletown", "Connecticut"),
("Middletown", "New York"),
("Middletown", "Ohio"),
("Middletown", "Pennsylvania"),
("Middletown", "Rhode Island"),
("Midland", "Michigan"),
("Midland", "Texas"),
("Midwest City", "Oklahoma"),
("Milan", "Ohio"),
("Milbank", "South Dakota"),
("Miles City", "Montana"),
("Milford", "Connecticut"),
("Milford", "Delaware"),
("Millburn", "New Jersey"),
("Milledgeville", "Georgia"),
("Millville", "New Jersey"),
("Milton", "Massachusetts"),
("Milwaukee", "Wisconsin"),
("Minden", "Nebraska"),
("Mineola", "New York"),
("Minneapolis", "Minnesota"),
("Minot", "North Dakota"),
("Mishawaka", "Indiana"),
("Mission", "Texas"),
("Missoula", "Montana"),
("Mitchell", "South Dakota"),
("Moab", "Utah"),
("Mobile", "Alabama"),
("Mobridge", "South Dakota"),
("Modesto", "California"),
("Moline", "Illinois"),
("Monett", "Missouri"),
("Monmouth", "Illinois"),
("Monroe", "Louisiana"),
("Monroe", "Michigan"),
("Monroeville", "Pennsylvania"),
("Montclair", "New Jersey"),
("Monterey", "California"),
("Montgomery", "Alabama"),
("Monticello", "Utah"),
("Montpelier", "Vermont"),
("Montrose", "Colorado"),
("Moore", "Oklahoma"),
("Moorhead", "Minnesota"),
("Morehead City", "North Carolina"),
("Morgan City", "Louisiana"),
("Morganton", "North Carolina"),
("Morgantown", "West Virginia"),
("Morrilton", "Arkansas"),
("Morristown", "New Jersey"),
("Morristown", "Tennessee"),
("Moscow", "Idaho"),
("Moses Lake", "Washington"),
("Moundsville", "West Virginia"),
("Mount Clemens", "Michigan"),
("Mount Holly", "New Jersey"),
("Mount Pleasant", "Iowa"),
("Mount Pleasant", "Michigan"),
("Mount Pleasant", "South Carolina"),
("Mount Vernon", "Illinois"),
("Mount Vernon", "New York"),
("Mount Vernon", "Ohio"),
("Mountain View", "California"),
("Muncie", "Indiana"),
("Mundelein", "Illinois"),
("Murfreesboro", "Tennessee"),
("Murray", "Utah"),
("Muscatine", "Iowa"),
("Muskegon", "Michigan"),
("Muskogee", "Oklahoma"),
("Myrtle Beach", "South Carolina"),
("Mystic", "Connecticut"),
("Nacogdoches", "Texas"),
("Nags Head", "North Carolina"),
("Nahant", "Massachusetts"),
("Nampa", "Idaho"),
("Nanticoke", "Pennsylvania"),
("Napa", "California"),
("Naperville", "Illinois"),
("Naples", "Florida"),
("Nappanee", "Indiana"),
("Narragansett", "Rhode Island"),
("Nashua", "New Hampshire"),
("Nashville", "Indiana"),
("Nashville", "Tennessee"),
("Natchez", "Mississippi"),
("Natchitoches", "Louisiana"),
("Natick", "Massachusetts"),
("Naugatuck", "Connecticut"),
("Nauvoo", "Illinois"),
("Nebraska City", "Nebraska"),
("Needles", "California"),
("Neenah", "Wisconsin"),
("Neosho", "Missouri"),
("Nephi", "Utah"),
("New Albany", "Indiana"),
("New Bedford", "Massachusetts"),
("New Bern", "North Carolina"),
("New Braunfels", "Texas"),
("New Britain", "Connecticut"),
("New Brunswick", "New Jersey"),
("New Castle", "Delaware"),
("New Castle", "Indiana"),
("New Castle", "Pennsylvania"),
("New Glarus", "Wisconsin"),
("New Harmony", "Indiana"),
("New Haven", "Connecticut"),
("New Hope", "Pennsylvania"),
("New Iberia", "Louisiana"),
("New Kensington", "Pennsylvania"),
("New London", "Connecticut"),
("New Madrid", "Missouri"),
("New Market", "Virginia"),
("New Martinsville", "West Virginia"),
("New Milford", "New Jersey"),
("New Orleans", "Louisiana"),
("New Paltz", "New York"),
("New Philadelphia", "Ohio"),
("New Rochelle", "New York"),
("New Smyrna Beach", "Florida"),
("New Ulm", "Minnesota"),
("New Windsor", "New York"),
("New York City", "New York"),
("Newark", "Delaware"),
("Newark", "New Jersey"),
("Newark", "Ohio"),
("Newberg", "Oregon"),
("Newburgh", "New York"),
("Newburyport", "Massachusetts"),
("Newcastle", "Wyoming"),
("Newport Beach", "California"),
("Newport News", "Virginia"),
("Newport", "Arkansas"),
("Newport", "Kentucky"),
("Newport", "Oregon"),
("Newport", "Rhode Island"),
("Newport", "Vermont"),
("Newton", "Iowa"),
("Newton", "Kansas"),
("Newton", "Massachusetts"),
("Niagara Falls", "New York"),
("Niles", "Michigan"),
("Niles", "Ohio"),
("Nogales", "Arizona"),
("Nome", "Alaska"),
("Norfolk", "Nebraska"),
("Norfolk", "Virginia"),
("Normal", "Illinois"),
("Norman", "Oklahoma"),
("Norris", "Tennessee"),
("Norristown", "Pennsylvania"),
("North Adams", "Massachusetts"),
("North Chicago", "Illinois"),
("North College Hill", "Ohio"),
("North Haven", "Connecticut"),
("North Hempstead", "New York"),
("North Kingstown", "Rhode Island"),
("North Las Vegas", "Nevada"),
("North Little Rock", "Arkansas"),
("North Platte", "Nebraska"),
("Northampton", "Massachusetts"),
("Northfield", "Minnesota"),
("Norton", "Massachusetts"),
("Norwalk", "California"),
("Norwalk", "Connecticut"),
("Norwalk", "Ohio"),
("Norwich", "Connecticut"),
("Norwood", "Massachusetts"),
("Novato", "California"),
("Nyack", "New York"),
("Oak Harbor", "Washington"),
("Oak Park", "Illinois"),
("Oak Ridge", "Tennessee"),
("Oakland", "California"),
("Oakland", "Maryland"),
("Oberlin", "Ohio"),
("Ocala", "Florida"),
("Ocean City", "Maryland"),
("Ocean City", "New Jersey"),
("Ocean Springs", "Mississippi"),
("Oceanside", "California"),
("Oconto", "Wisconsin"),
("Odessa", "Texas"),
("Ogden", "Utah"),
("Ogdensburg", "New York"),
("Oil City", "Pennsylvania"),
("Ojai", "California"),
("Oklahoma City", "Oklahoma"),
("Okmulgee", "Oklahoma"),
("Olathe", "Kansas"),
("Old Saybrook", "Connecticut"),
("Olean", "New York"),
("Olympia", "Washington"),
("Omaha", "Nebraska"),
("Oneida", "New York"),
("Oneonta", "New York"),
("Ontario", "California"),
("Ontario", "Oregon"),
("Opelika", "Alabama"),
("Opelousas", "Louisiana"),
("Oraibi", "Arizona"),
("Orange", "California"),
("Orange", "Connecticut"),
("Orange", "New Jersey"),
("Orange", "Texas"),
("Orangeburg", "South Carolina"),
("Orderville", "Utah"),
("Oregon City", "Oregon"),
("Oregon", "Illinois"),
("Orem", "Utah"),
("Orlando", "Florida"),
("Ormond Beach", "Florida"),
("Orono", "Maine"),
("Oroville", "California"),
("Osawatomie", "Kansas"),
("Osceola", "Arkansas"),
("Oshkosh", "Wisconsin"),
("Oskaloosa", "Iowa"),
("Ossining", "New York"),
("Oswego", "New York"),
("Ottawa", "Illinois"),
("Ottawa", "Kansas"),
("Ottumwa", "Iowa"),
("Ouray", "Colorado"),
("Overland Park", "Kansas"),
("Owatonna", "Minnesota"),
("Owensboro", "Kentucky"),
("Oxford", "Mississippi"),
("Oxnard", "California"),
("Oyster Bay", "New York"),
("Ozark", "Alabama"),
("Pacific Grove", "California"),
("Paducah", "Kentucky"),
("Pagosa Springs", "Colorado"),
("Painesville", "Ohio"),
("Palatine", "Illinois"),
("Palatka", "Florida"),
("Palm Bay", "Florida"),
("Palm Beach", "Florida"),
("Palm Springs", "California"),
("Palmdale", "California"),
("Palmer", "Alaska"),
("Palmyra", "New York"),
("Palo Alto", "California"),
("Pampa", "Texas"),
("Panama City", "Florida"),
("Panguitch", "Utah"),
("Paris", "Kentucky"),
("Paris", "Texas"),
("Park City", "Utah"),
("Park Forest", "Illinois"),
("Park Ridge", "Illinois"),
("Parkersburg", "West Virginia"),
("Parma", "Ohio"),
("Parsippany–Troy Hills", "New Jersey"),
("Pasadena", "California"),
("Pasadena", "Texas"),
("Pascagoula", "Mississippi"),
("Pasco", "Washington"),
("Pass Christian", "Mississippi"),
("Passaic", "New Jersey"),
("Paterson", "New Jersey"),
("Pauls Valley", "Oklahoma"),
("Pawhuska", "Oklahoma"),
("Pawtucket", "Rhode Island"),
("Payson", "Utah"),
("Peabody", "Massachusetts"),
("Pecos", "Texas"),
("Peekskill", "New York"),
("Pekin", "Illinois"),
("Pendleton", "Oregon"),
("Pensacola", "Florida"),
("Peoria", "Illinois"),
("Perry", "Oklahoma"),
("Perth Amboy", "New Jersey"),
("Peru", "Indiana"),
("Peshtigo", "Wisconsin"),
("Petaluma", "California"),
("Peterborough", "New Hampshire"),
("Petersburg", "Illinois"),
("Petersburg", "Virginia"),
("Petoskey", "Michigan"),
("Pharr", "Texas"),
("Phenix City", "Alabama"),
("Philadelphia", "Mississippi"),
("Philadelphia", "Pennsylvania"),
("Philippi", "West Virginia"),
("Phoenix", "Arizona"),
("Phoenixville", "Pennsylvania"),
("Pierre", "South Dakota"),
("Pine Bluff", "Arkansas"),
("Pinehurst", "North Carolina"),
("Pipestone", "Minnesota"),
("Piqua", "Ohio"),
("Pittsburg", "Kansas"),
("Pittsburgh", "Pennsylvania"),
("Pittsfield", "Massachusetts"),
("Plainfield", "New Jersey"),
("Plains", "Georgia"),
("Plainview", "Texas"),
("Plano", "Texas"),
("Plattsburgh", "New York"),
("Plattsmouth", "Nebraska"),
("Plymouth", "Indiana"),
("Plymouth", "Massachusetts"),
("Plymouth", "New Hampshire"),
("Plymouth", "Vermont"),
("Pocatello", "Idaho"),
("Point Pleasant", "West Virginia"),
("Point Roberts", "Washington"),
("Pomona", "California"),
("Pompano Beach", "Florida"),
("Ponca City", "Oklahoma"),
("Pontiac", "Illinois"),
("Pontiac", "Michigan"),
("Port Angeles", "Washington"),
("Port Arthur", "Texas"),
("Port Gibson", "Mississippi"),
("Port Hueneme", "California"),
("Port Huron", "Michigan"),
("Port Lavaca", "Texas"),
("Port Orford", "Oregon"),
("Port Washington", "New York"),
("Portage", "Wisconsin"),
("Portales", "New Mexico"),
("Portland", "Maine"),
("Portland", "Oregon"),
("Portsmouth", "New Hampshire"),
("Portsmouth", "Ohio"),
("Portsmouth", "Rhode Island"),
("Portsmouth", "Virginia"),
("Potsdam", "New York"),
("Pottstown", "Pennsylvania"),
("Pottsville", "Pennsylvania"),
("Poughkeepsie", "New York"),
("Powell", "Wyoming"),
("Prairie du Chien", "Wisconsin"),
("Prescott", "Arizona"),
("Presque Isle", "Maine"),
("Price", "Utah"),
("Prichard", "Alabama"),
("Priest River", "Idaho"),
("Princeton", "New Jersey"),
("Princeton", "West Virginia"),
("Prineville", "Oregon"),
("Providence", "Rhode Island"),
("Provincetown", "Massachusetts"),
("Provo", "Utah"),
("Pryor", "Oklahoma"),
("Pueblo", "Colorado"),
("Pullman", "Washington"),
("Put-in-Bay", "Ohio"),
("Puyallup", "Washington"),
("Queens", "New York"),
("Quincy", "Illinois"),
("Quincy", "Massachusetts"),
("Racine", "Wisconsin"),
("Raleigh", "North Carolina"),
("Rancho Cucamonga", "California"),
("Randolph", "Massachusetts"),
("Rantoul", "Illinois"),
("Rapid City", "South Dakota"),
("Raton", "New Mexico"),
("Rawlins", "Wyoming"),
("Reading", "Pennsylvania"),
("Red Bluff", "California"),
("Red Cloud", "Nebraska"),
("Red Wing", "Minnesota"),
("Redding", "California"),
("Redlands", "California"),
("Redmond", "Oregon"),
("Redmond", "Washington"),
("Redondo Beach", "California"),
("Redwood City", "California"),
("Reedsport", "Oregon"),
("Reno", "Nevada"),
("Rensselaer", "New York"),
("Renton", "Washington"),
("Reston", "Virginia"),
("Revere", "Massachusetts"),
("Rexburg", "Idaho"),
("Rhinelander", "Wisconsin"),
("Richardson", "Texas"),
("Richland", "Washington"),
("Richmond", "California"),
("Richmond", "Indiana"),
("Richmond", "Kentucky"),
("Richmond", "Virginia"),
("Ridgewood", "New Jersey"),
("Ripon", "Wisconsin"),
("River Forest", "Illinois"),
("Riverside", "California"),
("Riverton", "Wyoming"),
("Roanoke", "Virginia"),
("Rochester", "Minnesota"),
("Rochester", "New Hampshire"),
("Rochester", "New York"),
("Rock Hill", "South Carolina"),
("Rock Island", "Illinois"),
("Rock Springs", "Wyoming"),
("Rockford", "Illinois"),
("Rockland", "Maine"),
("Rockville", "Maryland"),
("Rocky Mount", "North Carolina"),
("Rogers", "Arkansas"),
("Rolla", "Missouri"),
("Rome", "Georgia"),
("Rome", "New York"),
("Romney", "West Virginia"),
("Roseburg", "Oregon"),
("Roselle", "New Jersey"),
("Roseville", "California"),
("Roswell", "New Mexico"),
("Rotterdam", "New York"),
("Royal Oak", "Michigan"),
("Rugby", "North Dakota"),
("Rumford", "Maine"),
("Ruston", "Louisiana"),
("Rutherford", "New Jersey"),
("Rutland", "Vermont"),
("Rye", "New York"),
("Saco", "Maine"),
("Sacramento", "California"),
("Sag Harbor", "New York"),
("Saginaw", "Michigan"),
("Saint Albans", "Vermont"),
("Saint Augustine", "Florida"),
("Saint Charles", "Missouri"),
("Saint Cloud", "Minnesota"),
("Saint George", "Utah"),
("Saint Ignace", "Michigan"),
("Saint Johnsbury", "Vermont"),
("Saint Joseph", "Michigan"),
("Saint Joseph", "Missouri"),
("Saint Louis", "Missouri"),
("Saint Martinville", "Louisiana"),
("Saint Marys City", "Maryland"),
("Saint Paul", "Minnesota"),
("Saint Petersburg", "Florida"),
("Sainte Genevieve", "Missouri"),
("Salem", "Illinois"),
("Salem", "Massachusetts"),
("Salem", "Missouri"),
("Salem", "New Hampshire"),
("Salem", "New Jersey"),
("Salem", "Ohio"),
("Salem", "Oregon"),
("Salina", "Kansas"),
("Salinas", "California"),
("Salisbury", "Maryland"),
("Salisbury", "North Carolina"),
("Sallisaw", "Oklahoma"),
("Salt Lake City", "Utah"),
("San Angelo", "Texas"),
("San Antonio", "Texas"),
("San Bernardino", "California"),
("San Clemente", "California"),
("San Diego", "California"),
("San Felipe", "Texas"),
("San Fernando", "California"),
("San Francisco", "California"),
("San Gabriel", "California"),
("San Jose", "California"),
("San Juan Capistrano", "California"),
("San Leandro", "California"),
("San Luis Obispo", "California"),
("San Marcos", "Texas"),
("San Marino", "California"),
("San Mateo", "California"),
("San Pedro", "California"),
("San Rafael", "California"),
("San Simeon", "California"),
("Sand Springs", "Oklahoma"),
("Sandusky", "Ohio"),
("Sandwich", "Massachusetts"),
("Sanford", "Florida"),
("Santa Ana", "California"),
("Santa Barbara", "California"),
("Santa Clara", "California"),
("Santa Clarita", "California"),
("Santa Claus", "Indiana"),
("Santa Cruz", "California"),
("Santa Fe", "New Mexico"),
("Santa Monica", "California"),
("Santa Rosa", "California"),
("Sapulpa", "Oklahoma"),
("Saranac Lake", "New York"),
("Sarasota", "Florida"),
("Saratoga Springs", "New York"),
("Saugus", "Massachusetts"),
("Sauk Centre", "Minnesota"),
("Sault Sainte Marie", "Michigan"),
("Sausalito", "California"),
("Savannah", "Georgia"),
("Scarborough", "Maine"),
("Scarsdale", "New York"),
("Schenectady", "New York"),
("Scottsboro", "Alabama"),
("Scottsdale", "Arizona"),
("Scranton", "Pennsylvania"),
("Searcy", "Arkansas"),
("Seaside", "Oregon"),
("Seattle", "Washington"),
("Sebring", "Florida"),
("Sedalia", "Missouri"),
("Selma", "Alabama"),
("Seminole", "Oklahoma"),
("Seneca Falls", "New York"),
("Seward", "Alaska"),
("Seymour", "Connecticut"),
("Shaker Heights", "Ohio"),
("Shamokin", "Pennsylvania"),
("Sharon", "Pennsylvania"),
("Sharon", "Vermont"),
("Shawnee", "Kansas"),
("Shawnee", "Oklahoma"),
("Shawneetown", "Illinois"),
("Sheboygan", "Wisconsin"),
("Sheffield", "Alabama"),
("Shelby", "North Carolina"),
("Shelbyville", "Indiana"),
("Shelbyville", "Tennessee"),
("Shelton", "Connecticut"),
("Shepherdstown", "West Virginia"),
("Sheridan", "Wyoming"),
("Sherman", "Texas"),
("Shiprock", "New Mexico"),
("Shreveport", "Louisiana"),
("Sidney", "Nebraska"),
("Sierra Vista", "Arizona"),
("Silver City", "New Mexico"),
("Silver Spring", "Maryland"),
("Silverton", "Colorado"),
("Simi Valley", "California"),
("Simsbury", "Connecticut"),
("Sioux City", "Iowa"),
("Sioux Falls", "South Dakota"),
("Sitka", "Alaska"),
("Skagway", "Alaska"),
("Skokie", "Illinois"),
("Smith Center", "Kansas"),
("Smyrna", "Delaware"),
("Socorro", "New Mexico"),
("Somersworth", "New Hampshire"),
("Somerville", "Massachusetts"),
("Somerville", "New Jersey"),
("Sonoma", "California"),
("South Bend", "Indiana"),
("South Charleston", "West Virginia"),
("South Hadley", "Massachusetts"),
("South Holland", "Illinois"),
("South Kingstown", "Rhode Island"),
("South Orange Village", "New Jersey"),
("South Saint Paul", "Minnesota"),
("South San Francisco", "California"),
("Southampton", "New York"),
("Southington", "Connecticut"),
("Spanish Fork", "Utah"),
("Sparks", "Nevada"),
("Spartanburg", "South Carolina"),
("Spearfish", "South Dakota"),
("Spokane", "Washington"),
("Spring Green", "Wisconsin"),
("Springfield", "Illinois"),
("Springfield", "Massachusetts"),
("Springfield", "Missouri"),
("Springfield", "Ohio"),
("Springfield", "Oregon"),
("Springville", "Utah"),
("Stamford", "Connecticut"),
("Starkville", "Mississippi"),
("State College", "Pennsylvania"),
("Staten Island", "New York"),
("Staunton", "Virginia"),
("Steamboat Springs", "Colorado"),
("Sterling", "Colorado"),
("Steubenville", "Ohio"),
("Stevens Point", "Wisconsin"),
("Stillwater", "Minnesota"),
("Stillwater", "Oklahoma"),
("Stockbridge", "Massachusetts"),
("Stockton", "California"),
("Stonington", "Connecticut"),
("Stony Brook", "New York"),
("Stony Point", "New York"),
("Stoughton", "Massachusetts"),
("Stratford", "Connecticut"),
("Streator", "Illinois"),
("Stroudsburg", "Pennsylvania"),
("Sturbridge", "Massachusetts"),
("Sturgeon Bay", "Wisconsin"),
("Sturgis", "South Dakota"),
("Stuttgart", "Arkansas"),
("Sudbury", "Massachusetts"),
("Suffolk", "Virginia"),
("Summersville", "West Virginia"),
("Summit", "Illinois"),
("Sumter", "South Carolina"),
("Sun Valley", "Idaho"),
("Sunbury", "Pennsylvania"),
("Sunnyvale", "California"),
("Superior", "Wisconsin"),
("Susanville", "California"),
("Swarthmore", "Pennsylvania"),
("Sweetwater", "Texas"),
("Sylacauga", "Alabama"),
("Syracuse", "New York"),
("Tacoma", "Washington"),
("Tahlequah", "Oklahoma"),
("Takoma Park", "Maryland"),
("Talladega", "Alabama"),
("Tallahassee", "Florida"),
("Tamaqua", "Pennsylvania"),
("Tampa", "Florida"),
("Taos", "New Mexico"),
("Tarpon Springs", "Florida"),
("Tarrytown", "New York"),
("Taunton", "Massachusetts"),
("Telluride", "Colorado"),
("Tempe", "Arizona"),
("Temple", "Texas"),
("Ten Sleep", "Wyoming"),
("Terre Haute", "Indiana"),
("Tewksbury", "Massachusetts"),
("Texarkana", "Texas"),
("Texas City", "Texas"),
("The Dalles", "Oregon"),
("The Village", "Oklahoma"),
("Thermopolis", "Wyoming"),
("Thibodaux", "Louisiana"),
("Thousand Oaks", "California"),
("Ticonderoga", "New York"),
("Tiffin", "Ohio"),
("Tillamook", "Oregon"),
("Titusville", "Florida"),
("Titusville", "Pennsylvania"),
("Tiverton", "Rhode Island"),
("Toccoa", "Georgia"),
("Toledo", "Ohio"),
("Tombstone", "Arizona"),
("Tonawanda", "New York"),
("Tooele", "Utah"),
("Topeka", "Kansas"),
("Torrance", "California"),
("Torrington", "Connecticut"),
("Torrington", "Wyoming"),
("Totowa", "New Jersey"),
("Towson", "Maryland"),
("Traverse City", "Michigan"),
("Trenton", "Michigan"),
("Trenton", "New Jersey"),
("Trinidad", "Colorado"),
("Troy", "Alabama"),
("Troy", "New York"),
("Truro", "Massachusetts"),
("Truth or Consequences", "New Mexico"),
("Tucson", "Arizona"),
("Tucumcari", "New Mexico"),
("Tullahoma", "Tennessee"),
("Tulsa", "Oklahoma"),
("Tupelo", "Mississippi"),
("Turlock", "California"),
("Tuscaloosa", "Alabama"),
("Tuscumbia", "Alabama"),
("Tuskegee", "Alabama"),
("Twin Falls", "Idaho"),
("Tyler", "Texas"),
("Ukiah", "California"),
("Union City", "New Jersey"),
("Union", "New Jersey"),
("Union", "South Carolina"),
("Uniontown", "Pennsylvania"),
("Urbana", "Illinois"),
("Urbana", "Ohio"),
("Utica", "New York"),
("Uvalde", "Texas"),
("Vail", "Colorado"),
("Valdez", "Alaska"),
("Valdosta", "Georgia"),
("Vallejo", "California"),
("Valley City", "North Dakota"),
("Valparaiso", "Indiana"),
("Van Buren", "Arkansas"),
("Vancouver", "Washington"),
("Vandalia", "Illinois"),
("Venice", "Florida"),
("Ventura", "California"),
("Vermillion", "South Dakota"),
("Vernal", "Utah"),
("Vicksburg", "Mississippi"),
("Victoria", "Texas"),
("Victorville", "California"),
("Vincennes", "Indiana"),
("Vineland", "New Jersey"),
("Vinita", "Oklahoma"),
("Virden", "Illinois"),
("Virginia Beach", "Virginia"),
("Virginia City", "Montana"),
("Virginia City", "Nevada"),
("Virginia", "Minnesota"),
("Visalia", "California"),
("Wabash", "Indiana"),
("Waco", "Texas"),
("Wahiawa", "Hawaii"),
("Wahpeton", "North Dakota"),
("Wailuku", "Hawaii"),
("Waimea", "Hawaii"),
("Walla Walla", "Washington"),
("Wallingford", "Connecticut"),
("Walnut Creek", "California"),
("Walpi", "Arizona"),
("Walsenburg", "Colorado"),
("Warm Springs", "Georgia"),
("Warner Robins", "Georgia"),
("Warren", "Michigan"),
("Warren", "Ohio"),
("Warren", "Pennsylvania"),
("Warren", "Rhode Island"),
("Warrensburg", "Missouri"),
("Warwick", "Rhode Island"),
("Washington", "Georgia"),
("Washington", "North Carolina"),
("Washington", "Pennsylvania"),
("Waterbury", "Connecticut"),
("Waterford", "Connecticut"),
("Waterloo", "Iowa"),
("Watertown", "Connecticut"),
("Watertown", "Massachusetts"),
("Watertown", "New York"),
("Watertown", "South Dakota"),
("Waterville", "Maine"),
("Watervliet", "New York"),
("Watkins Glen", "New York"),
("Watts", "California"),
("Waukegan", "Illinois"),
("Waukesha", "Wisconsin"),
("Wausau", "Wisconsin"),
("Wauwatosa", "Wisconsin"),
("Waycross", "Georgia"),
("Wayne", "New Jersey"),
("Waynesboro", "Virginia"),
("Weatherford", "Texas"),
("Webster City", "Iowa"),
("Webster", "Massachusetts"),
("Weehawken", "New Jersey"),
("Weirton", "West Virginia"),
("Welch", "West Virginia"),
("Wellesley", "Massachusetts"),
("Wellfleet", "Massachusetts"),
("Wellsburg", "West Virginia"),
("Wenatchee", "Washington"),
("West Allis", "Wisconsin"),
("West Bend", "Wisconsin"),
("West Bridgewater", "Massachusetts"),
("West Chester", "Pennsylvania"),
("West Covina", "California"),
("West Des Moines", "Iowa"),
("West Hartford", "Connecticut"),
("West Haven", "Connecticut"),
("West Lafayette", "Indiana"),
("West Memphis", "Arkansas"),
("West New York", "New Jersey"),
("West Orange", "New Jersey"),
("West Palm Beach", "Florida"),
("West Plains", "Missouri"),
("West Point", "Mississippi"),
("West Seneca", "New York"),
("West Springfield", "Massachusetts"),
("Westerly", "Rhode Island"),
("Westfield", "Massachusetts"),
("Westminster", "Colorado"),
("Westminster", "Maryland"),
("Weston", "West Virginia"),
("Westport", "Connecticut"),
("Wethersfield", "Connecticut"),
("Wewoka", "Oklahoma"),
("Weymouth", "Massachusetts"),
("Wheaton", "Illinois"),
("Wheeling", "West Virginia"),
("White Plains", "New York"),
("White Springs", "Florida"),
("White Sulphur Springs", "West Virginia"),
("Whitman", "Massachusetts"),
("Whittier", "California"),
("Wichita Falls", "Texas"),
("Wichita", "Kansas"),
("Wickford", "Rhode Island"),
("Wilkes-Barre", "Pennsylvania"),
("Williamsburg", "Virginia"),
("Williamson", "West Virginia"),
("Williamsport", "Pennsylvania"),
("Williamstown", "Massachusetts"),
("Willimantic", "Connecticut"),
("Willingboro", "New Jersey"),
("Williston", "North Dakota"),
("Willmar", "Minnesota"),
("Wilmette", "Illinois"),
("Wilmington", "Delaware"),
("Wilmington", "North Carolina"),
("Wilson", "North Carolina"),
("Winchester", "Virginia"),
("Windham", "Connecticut"),
("Window Rock", "Arizona"),
("Windsor Locks", "Connecticut"),
("Windsor", "Connecticut"),
("Winnemucca", "Nevada"),
("Winnetka", "Illinois"),
("Winona", "Minnesota"),
("Winooski", "Vermont"),
("Winslow", "Arizona"),
("Winsted", "Connecticut"),
("Winston-Salem", "North Carolina"),
("Winter Haven", "Florida"),
("Winter Park", "Florida"),
("Wisconsin Dells", "Wisconsin"),
("Woburn", "Massachusetts"),
("Wood River", "Illinois"),
("Woodbridge", "New Jersey"),
("Woodland", "California"),
("Woods Hole", "Massachusetts"),
("Woodstock", "New York"),
("Woodward", "Oklahoma"),
("Woonsocket", "Rhode Island"),
("Wooster", "Ohio"),
("Worcester", "Massachusetts"),
("Worland", "Wyoming"),
("Worthington", "Ohio"),
("Wyandotte", "Michigan"),
("Xenia", "Ohio"),
("Yakima", "Washington"),
("Yankton", "South Dakota"),
("Yazoo City", "Mississippi"),
("Yellow Springs", "Ohio"),
("Yonkers", "New York"),
("Yorba Linda", "California"),
("York", "Maine"),
("York", "Pennsylvania"),
("Youngstown", "Ohio"),
("Ypsilanti", "Michigan"),
("Ysleta", "Texas"),
("Yuba City", "California"),
("Yuma", "Arizona"),
("Zanesville", "Ohio"),
("Zion", "Illinois")
;



# =====================================================================================================================
# SHOW Data
# =====================================================================================================================
SELECT * FROM `MyPeople`.`city`;
